---
- name: general deployment
  hosts: all
  tasks:
    - name: deploy ssh keys remotely
      include: plays/deploy_ssh.yaml
    - name: copy host file
      include: plays/copy_hosts.yaml
    - name: base vars
      include: plays/vars.yaml
