---
#- name: run local facts setup
#  hosts: all
#  gather_facts: true
#  roles:
#    - local_facts

- name: lets gooooooooo
  hosts: all
  become: true
  tasks:
    - name: ssh assert
      include_tasks: plays/assert.yaml
#     - name: execute shell cmds
#       include: plays/shell.yaml
#    - name: copy sepermit
#      include: plays/command.yaml
#    - name: install apache
#      include_tasks: plays/webserver.yaml
#    - name: deploy ssh keys remotely
#      include: plays/deploy_ssh.yaml
#    - name: copy host file
#      include: plays/copy_hosts.yaml
#    - name: base vars
#      include: plays/vars.yaml
#    - name: add users
#      include: plays/useradd.yaml
#    - name: template example
#      include: plays/template.yaml
#    - name: linein example
#      include: plays/lineinfile_example.yaml
#    - name: conditional example
#      include_tasks: plays/conditional.yaml
#    - name: setting custom facts
#      include_tasks: plays/set_facts.yaml

  handlers:
    - name: restart apache
      service:
        name: httpd
        state: restarted
