---
- name: create hardware report
  ansible.builtin.file:
    path: /tmp/report.txt
    state: touch

- name: create ubuntu file if condition matches
  command: curl -s http://169.254.169.254/latest/meta-data/instance-type
  register: instance_type

- name: populate file when t2.nano
  ansible.builtin.lineinfile:
    path: /tmp/report.txt
    line: 'teenytiny' 
  when: instance_type.stdout == "t2.nano"

- name: populate file when t2.micro
  ansible.builtin.lineinfile:
    path: /tmp/report.txt
    line: 'big'
  when: instance_type.stdout == "t2.micro"

- name: register var for nano
  ansible.builtin.command: cat /tmp/report.txt
  register: reportoutput

- name: Am I big?
  ansible.builtin.file:
    path: /tmp/I_AM_BIG
    state: touch
  when: reportoutput.stdout == "big"

- name: Am I small?
  ansible.builtin.file:
    path: /tmp/I_AM_BIG
    state: touch
  when: reportoutput.stdout == "teenytiny"
