---
- name: update sshd_config X11
  ansible.builtin.lineinfile:
    path: /tmp/sshd_config
    regexp: '^X11Forwarding'
    line: X11Forwarding no

- name: update sshd_config passwords
  ansible.builtin.lineinfile:
    path: /tmp/sshd_config
    insertafter: '^PasswordAuthentication yes'
    regexp: '^#PermitEmptyPasswords no'
    line: 'PermitEmptyPasswords yes'
